/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, October 12, 2021 at 10:43:57 PM Eastern Daylight Time
* Operating System: Version 11.1 (Build 20C5061b)
* Image Source: /System/Library/PrivateFrameworks/IMCore.framework/Versions/A/IMCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSUbiquitousKeyValueStore, NSOrderedSet;

@interface IMPinnedConversationsController : NSObject {

    char _hasCompletedInitialization;
    char _hasDefferedPinnedConversationsDidChangeNotification;
    NSUbiquitousKeyValueStore* _dataStore;
    NSOrderedSet* _pinnedConversationIdentifierSet;
    long long _numberOfPendingForceSyncs;

}

@property (nonatomic,readonly) NSUbiquitousKeyValueStore * dataStore;                               //@synthesize dataStore=_dataStore - In the implementation block
@property (nonatomic,retain) NSOrderedSet * pinnedConversationIdentifierSet;                        //@synthesize pinnedConversationIdentifierSet=_pinnedConversationIdentifierSet - In the implementation block
@property (assign,nonatomic) char hasCompletedInitialization;                                       //@synthesize hasCompletedInitialization=_hasCompletedInitialization - In the implementation block
@property (assign,nonatomic) char hasDefferedPinnedConversationsDidChangeNotification;              //@synthesize hasDefferedPinnedConversationsDidChangeNotification=_hasDefferedPinnedConversationsDidChangeNotification - In the implementation block
@property (assign,nonatomic) long long numberOfPendingForceSyncs;                                   //@synthesize numberOfPendingForceSyncs=_numberOfPendingForceSyncs - In the implementation block
+(id)sharedInstance;
+(id)requiredKeys;
+(long long)currentPinConfigurationVersion;
+(unsigned long long)maximumNumberOfPinnedConversations;
+(id)_forceSyncDispatchQueue;
+(id)_ubiquitousDispatchQueue;
-(id)init;
-(char)shouldSync;
-(NSUbiquitousKeyValueStore *)dataStore;
-(void)_postDeferredPinnedConversationsDidChangeNotificationIfNecessary;
-(void)handleNSUbiquitousKeyValueStoreDidChangeExternallyNotification:(id)arg1 ;
-(void)imCloudKitHooksSetEnabledDidReturn:(id)arg1 ;
-(void)performOneTimeFetchIfNecessary;
-(void)fetchPinnedConversationIdentifiersFromLocalStore;
-(void)synchronizeLocalDataStore;
-(id)_ubiquitousPinConfigurationInStore:(id)arg1 ;
-(id)_locallyStoredPinConfiguration;
-(id)mostUpToDatePinConfigurationByComparingPinConfiguration:(id)arg1 toOtherPinConfiguration:(id)arg2 ;
-(id)pinnedConversationIdentifiersFromPinConfiguration:(id)arg1 ;
-(void)setPinnedConversationIdentifiers:(id)arg1 withUpdateReason:(id)arg2 shouldUpdateStores:(char)arg3 ;
-(void)_updateLocalStoreWithPinConfiguration:(id)arg1 ;
-(id)_dictionaryWithPinnedConversationIdentifiers:(id)arg1 updateReason:(id)arg2 timestamp:(id)arg3 ;
-(NSOrderedSet *)pinnedConversationIdentifierSet;
-(char)pinnedConversationsContainsPinningIdentifier:(id)arg1 ;
-(id)dictionaryWithPinnedConversationIdentifiers:(id)arg1 updateReason:(id)arg2 ;
-(void)updateStoresWithPinConfiguration:(id)arg1 ;
-(void)_postPinnedConversationsDidChangeNotification;
-(void)conversationsWereDeletedWithIdentifiers:(id)arg1 ;
-(char)pinConfigurationIsValid:(id)arg1 ;
-(char)pinConfigurationHasCurrentVersion:(id)arg1 ;
-(void)fetchMostUpToDatePinConfiguration:(/*^block*/id)arg1 ;
-(long long)numberOfPendingForceSyncs;
-(void)setNumberOfPendingForceSyncs:(long long)arg1 ;
-(void)_updateUbiquitousStoreWithPinConfiguration:(id)arg1 completion:(/*^block*/id)arg2 ;
-(char)shouldWriteProposedPinConfiguration:(id)arg1 toUbiquitousStoreWithExistingPinConfiguration:(id)arg2 ;
-(char)shouldUpdateExistingPinConfig:(id)arg1 withProposedPinConfig:(id)arg2 ;
-(void)forceSynchronizeUbiquitousStore;
-(void)_fetchUbiquitousPinConfiguration:(/*^block*/id)arg1 ;
-(id)pinConfigurationWithCurrentVersionForPinConfiguration:(id)arg1 ;
-(char)pinConfigurationHasCompatibleVersion:(id)arg1 ;
-(void)_updatePinningIdentifiersUsingOldToNewPinningIdentifierMapIfNecessary:(id)arg1 ;
-(char)pinnedConversationsContainsChat:(id)arg1 ;
-(void)setPinnedConversationIdentifiers:(id)arg1 withUpdateReason:(id)arg2 ;
-(void)conversationWasDeletedWithIdentifier:(id)arg1 ;
-(id)pinnedConversationIdentifiers;
-(void)setPinnedConversationIdentifierSet:(NSOrderedSet *)arg1 ;
-(char)hasCompletedInitialization;
-(void)setHasCompletedInitialization:(char)arg1 ;
-(char)hasDefferedPinnedConversationsDidChangeNotification;
-(void)setHasDefferedPinnedConversationsDidChangeNotification:(char)arg1 ;
@end

