/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, October 12, 2021 at 10:43:57 PM Eastern Daylight Time
* Operating System: Version 11.1 (Build 20C5061b)
* Image Source: /System/Library/PrivateFrameworks/IMCore.framework/Versions/A/IMCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSString, IMBalloonPluginDataSource;


@protocol IMPluginChatItemProtocol <NSObject>
@property (nonatomic,retain,readonly) NSString * type;
@property (nonatomic,retain,readonly) IMBalloonPluginDataSource * dataSource;
@property (nonatomic,readonly) char isFromMe;
@required
-(NSString *)type;
-(IMBalloonPluginDataSource *)dataSource;
-(char)isFromMe;

@end
