//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>

@class CPActivitySessionManager, CPApplicationPolicyManager, CPAudioRoutePolicyManager, CPSystemStateObserver, CSDConversationParticipant, CSDFaceTimeInviteDemuxer, CSDIDSGroupSession, CXCallFailureContext, NSArray, NSDate, NSDictionary, NSMutableArray, NSMutableDictionary, NSMutableSet, NSNumber, NSSet, NSString, NSUUID, TUCallScreenShareAttributes, TUConversation, TUConversationActivitySession, TUConversationLink, TUConversationMember, TUConversationParticipant, TUConversationProvider, TUConversationReport, TUHandle, TUVideoDeviceController;
@protocol CSDAVCSession, CSDConversationDelegate, CSDConversationServerBag, OS_dispatch_queue, TUFeatureFlags;

@interface CSDConversation : NSObject
{
    _Bool _relaying;    // 8 = 0x8
    _Bool _fromStorage;    // 9 = 0x9
    _Bool _video;    // 10 = 0xa
    _Bool _hasReceivedLetMeInRequest;    // 11 = 0xb
    _Bool _locallyCreated;    // 12 = 0xc
    _Bool _hasJoined;    // 13 = 0xd
    _Bool _ignoreLMIRequests;    // 14 = 0xe
    _Bool _waitingToPruneParticipants;    // 15 = 0xf
    _Bool _avcSessionInProgress;    // 16 = 0x10
    _Bool _forceExpanseEnabled;    // 17 = 0x11
    NSSet *_memberIdentifiers;    // 24 = 0x18
    id <CSDConversationDelegate> _delegate;    // 32 = 0x20
    NSUUID *_UUID;    // 40 = 0x28
    NSUUID *_groupUUID;    // 48 = 0x30
    TUConversationLink *_link;    // 56 = 0x38
    NSUUID *_messagesGroupUUID;    // 64 = 0x40
    long long _state;    // 72 = 0x48
    long long _letMeInRequestState;    // 80 = 0x50
    TUConversationMember *_localLightweightSecondaryMember;    // 88 = 0x58
    TUHandle *_initiator;    // 96 = 0x60
    TUConversationMember *_localMember;    // 104 = 0x68
    NSSet *_remoteMembers;    // 112 = 0x70
    NSSet *_lightweightMembers;    // 120 = 0x78
    NSSet *_pendingMembers;    // 128 = 0x80
    NSSet *_kickedMembers;    // 136 = 0x88
    NSSet *_rejectedMembers;    // 144 = 0x90
    NSSet *_otherInvitedHandles;    // 152 = 0x98
    TUConversationActivitySession *_stagedActivitySession;    // 160 = 0xa0
    NSString *_messagesGroupName;    // 168 = 0xa8
    CPActivitySessionManager *_activitySessionManager;    // 176 = 0xb0
    TUConversationReport *_report;    // 184 = 0xb8
    id <TUFeatureFlags> _featureFlags;    // 192 = 0xc0
    NSObject<OS_dispatch_queue> *_queue;    // 200 = 0xc8
    NSMutableDictionary *_activeRemoteParticipantsByIdentifier;    // 208 = 0xd0
    NSMutableDictionary *_activeLightweightParticipantsByIdentifier;    // 216 = 0xd8
    NSMutableSet *_kickedParticipants;    // 224 = 0xe0
    CSDIDSGroupSession *_idsSession;    // 232 = 0xe8
    id <CSDAVCSession> _avcSession;    // 240 = 0xf0
    NSNumber *_expectedAudioEnabled;    // 248 = 0xf8
    NSNumber *_expectedVideoEnabled;    // 256 = 0x100
    NSNumber *_expectedScreenEnabled;    // 264 = 0x108
    NSNumber *_expectedVideoPaused;    // 272 = 0x110
    NSNumber *_expectedAudioPaused;    // 280 = 0x118
    NSDictionary *_activeParticipantDestinationsByIdentifier;    // 288 = 0x120
    NSDictionary *_activeLightweightParticipantDestinationsByIdentifier;    // 296 = 0x128
    NSSet *_serverProvidedParticipantIdentifiers;    // 304 = 0x130
    NSSet *_serverProvidedLightweightParticipantIdentifiers;    // 312 = 0x138
    NSDate *_lastRebroadcastTime;    // 320 = 0x140
    unsigned long long _rebroadcastTimeThreshold;    // 328 = 0x148
    TUVideoDeviceController *_videoDeviceController;    // 336 = 0x150
    NSMutableDictionary *_virtualParticipantsByPluginName;    // 344 = 0x158
    CSDFaceTimeInviteDemuxer *_faceTimeInviteDemuxer;    // 352 = 0x160
    NSMutableDictionary *_pendingKickedMembersByIdentifier;    // 360 = 0x168
    NSMutableSet *_pendingAllowedMembers;    // 368 = 0x170
    unsigned long long _kickMemberRetryCount;    // 376 = 0x178
    NSArray *_currentParticipantPresentationContexts;    // 384 = 0x180
    CSDConversationParticipant *_splitSessionSecondary;    // 392 = 0x188
    CPApplicationPolicyManager *_applicationLaunchPolicyManager;    // 400 = 0x190
    CPAudioRoutePolicyManager *_audioRoutePolicyManager;    // 408 = 0x198
    CPSystemStateObserver *_sharePlaySystemStateObserver;    // 416 = 0x1a0
    id _downgradeToOneToOneAfterDelayBlock;    // 424 = 0x1a8
    NSSet *_remoteMemberHandles;    // 432 = 0x1b0
    NSSet *_pendingMemberHandles;    // 440 = 0x1b8
    NSSet *_memberHandlesEligibleForLinkApproval;    // 448 = 0x1c0
    NSMutableArray *_memberHandlesAwaitingInvitesToLink;    // 456 = 0x1c8
    id <CSDConversationServerBag> _serverBag;    // 464 = 0x1d0
    id _avcSessionCreationBlock;    // 472 = 0x1d8
    NSObject *_reportingHierarchyToken;    // 480 = 0x1e0
    NSObject *_reportingHierarchySubToken;    // 488 = 0x1e8
    NSMutableDictionary *_inflightAVCBlobRecoveryBlocksByIdentifier;    // 496 = 0x1f0
    id _timeoutBlock;    // 504 = 0x1f8
    id _participantRefreshBlock;    // 512 = 0x200
    NSSet *_invitationPreferences;    // 520 = 0x208
    TUCallScreenShareAttributes *_screenShareAttributes;    // 528 = 0x210
    TUConversationProvider *_provider;    // 536 = 0x218
    CXCallFailureContext *_failureContext;    // 544 = 0x220
}

@property(retain, nonatomic) CXCallFailureContext *failureContext; // @synthesize failureContext=_failureContext;
@property(retain, nonatomic) TUConversationProvider *provider; // @synthesize provider=_provider;
@property(nonatomic) TUCallScreenShareAttributes *screenShareAttributes; // @synthesize screenShareAttributes=_screenShareAttributes;
@property(copy, nonatomic) NSSet *invitationPreferences; // @synthesize invitationPreferences=_invitationPreferences;
@property(nonatomic) _Bool forceExpanseEnabled; // @synthesize forceExpanseEnabled=_forceExpanseEnabled;
@property(nonatomic) _Bool avcSessionInProgress; // @synthesize avcSessionInProgress=_avcSessionInProgress;
@property(copy, nonatomic) id participantRefreshBlock; // @synthesize participantRefreshBlock=_participantRefreshBlock;
@property(copy, nonatomic) id timeoutBlock; // @synthesize timeoutBlock=_timeoutBlock;
@property(readonly, copy, nonatomic) NSMutableDictionary *inflightAVCBlobRecoveryBlocksByIdentifier; // @synthesize inflightAVCBlobRecoveryBlocksByIdentifier=_inflightAVCBlobRecoveryBlocksByIdentifier;
@property(retain, nonatomic) NSObject *reportingHierarchySubToken; // @synthesize reportingHierarchySubToken=_reportingHierarchySubToken;
@property(retain, nonatomic) NSObject *reportingHierarchyToken; // @synthesize reportingHierarchyToken=_reportingHierarchyToken;
@property(copy, nonatomic) id avcSessionCreationBlock; // @synthesize avcSessionCreationBlock=_avcSessionCreationBlock;
@property(retain, nonatomic) id <CSDConversationServerBag> serverBag; // @synthesize serverBag=_serverBag;
@property(copy, nonatomic) NSMutableArray *memberHandlesAwaitingInvitesToLink; // @synthesize memberHandlesAwaitingInvitesToLink=_memberHandlesAwaitingInvitesToLink;
@property(copy, nonatomic) NSSet *memberHandlesEligibleForLinkApproval; // @synthesize memberHandlesEligibleForLinkApproval=_memberHandlesEligibleForLinkApproval;
@property(copy, nonatomic) NSSet *pendingMemberHandles; // @synthesize pendingMemberHandles=_pendingMemberHandles;
@property(copy, nonatomic) NSSet *remoteMemberHandles; // @synthesize remoteMemberHandles=_remoteMemberHandles;
@property(copy, nonatomic) id downgradeToOneToOneAfterDelayBlock; // @synthesize downgradeToOneToOneAfterDelayBlock=_downgradeToOneToOneAfterDelayBlock;
@property(retain, nonatomic) CPSystemStateObserver *sharePlaySystemStateObserver; // @synthesize sharePlaySystemStateObserver=_sharePlaySystemStateObserver;
@property(retain, nonatomic) CPAudioRoutePolicyManager *audioRoutePolicyManager; // @synthesize audioRoutePolicyManager=_audioRoutePolicyManager;
@property(retain, nonatomic) CPApplicationPolicyManager *applicationLaunchPolicyManager; // @synthesize applicationLaunchPolicyManager=_applicationLaunchPolicyManager;
@property(retain, nonatomic) CSDConversationParticipant *splitSessionSecondary; // @synthesize splitSessionSecondary=_splitSessionSecondary;
@property(retain, nonatomic) NSArray *currentParticipantPresentationContexts; // @synthesize currentParticipantPresentationContexts=_currentParticipantPresentationContexts;
@property(nonatomic) unsigned long long kickMemberRetryCount; // @synthesize kickMemberRetryCount=_kickMemberRetryCount;
@property(retain, nonatomic) NSMutableSet *pendingAllowedMembers; // @synthesize pendingAllowedMembers=_pendingAllowedMembers;
@property(retain, nonatomic) NSMutableDictionary *pendingKickedMembersByIdentifier; // @synthesize pendingKickedMembersByIdentifier=_pendingKickedMembersByIdentifier;
@property(readonly, nonatomic) CSDFaceTimeInviteDemuxer *faceTimeInviteDemuxer; // @synthesize faceTimeInviteDemuxer=_faceTimeInviteDemuxer;
@property(readonly, nonatomic) NSMutableDictionary *virtualParticipantsByPluginName; // @synthesize virtualParticipantsByPluginName=_virtualParticipantsByPluginName;
@property(readonly, nonatomic) TUVideoDeviceController *videoDeviceController; // @synthesize videoDeviceController=_videoDeviceController;
@property(nonatomic) unsigned long long rebroadcastTimeThreshold; // @synthesize rebroadcastTimeThreshold=_rebroadcastTimeThreshold;
@property(copy, nonatomic) NSDate *lastRebroadcastTime; // @synthesize lastRebroadcastTime=_lastRebroadcastTime;
@property(nonatomic, getter=isWaitingToPruneParticipants) _Bool waitingToPruneParticipants; // @synthesize waitingToPruneParticipants=_waitingToPruneParticipants;
@property(copy, nonatomic) NSSet *serverProvidedLightweightParticipantIdentifiers; // @synthesize serverProvidedLightweightParticipantIdentifiers=_serverProvidedLightweightParticipantIdentifiers;
@property(copy, nonatomic) NSSet *serverProvidedParticipantIdentifiers; // @synthesize serverProvidedParticipantIdentifiers=_serverProvidedParticipantIdentifiers;
@property(copy, nonatomic) NSDictionary *activeLightweightParticipantDestinationsByIdentifier; // @synthesize activeLightweightParticipantDestinationsByIdentifier=_activeLightweightParticipantDestinationsByIdentifier;
@property(copy, nonatomic) NSDictionary *activeParticipantDestinationsByIdentifier; // @synthesize activeParticipantDestinationsByIdentifier=_activeParticipantDestinationsByIdentifier;
@property(retain, nonatomic) NSNumber *expectedAudioPaused; // @synthesize expectedAudioPaused=_expectedAudioPaused;
@property(retain, nonatomic) NSNumber *expectedVideoPaused; // @synthesize expectedVideoPaused=_expectedVideoPaused;
@property(retain, nonatomic) NSNumber *expectedScreenEnabled; // @synthesize expectedScreenEnabled=_expectedScreenEnabled;
@property(retain, nonatomic) NSNumber *expectedVideoEnabled; // @synthesize expectedVideoEnabled=_expectedVideoEnabled;
@property(retain, nonatomic) NSNumber *expectedAudioEnabled; // @synthesize expectedAudioEnabled=_expectedAudioEnabled;
@property(retain, nonatomic) id <CSDAVCSession> avcSession; // @synthesize avcSession=_avcSession;
@property(readonly, nonatomic) CSDIDSGroupSession *idsSession; // @synthesize idsSession=_idsSession;
@property(retain, nonatomic) NSMutableSet *kickedParticipants; // @synthesize kickedParticipants=_kickedParticipants;
@property(retain, nonatomic) NSMutableDictionary *activeLightweightParticipantsByIdentifier; // @synthesize activeLightweightParticipantsByIdentifier=_activeLightweightParticipantsByIdentifier;
@property(readonly, nonatomic) NSMutableDictionary *activeRemoteParticipantsByIdentifier; // @synthesize activeRemoteParticipantsByIdentifier=_activeRemoteParticipantsByIdentifier;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(readonly, nonatomic) id <TUFeatureFlags> featureFlags; // @synthesize featureFlags=_featureFlags;
@property(readonly, nonatomic) TUConversationReport *report; // @synthesize report=_report;
@property(retain, nonatomic) CPActivitySessionManager *activitySessionManager; // @synthesize activitySessionManager=_activitySessionManager;
@property(copy, nonatomic) NSString *messagesGroupName; // @synthesize messagesGroupName=_messagesGroupName;
@property(retain, nonatomic) TUConversationActivitySession *stagedActivitySession; // @synthesize stagedActivitySession=_stagedActivitySession;
@property(nonatomic) _Bool ignoreLMIRequests; // @synthesize ignoreLMIRequests=_ignoreLMIRequests;
@property(copy, nonatomic) NSSet *otherInvitedHandles; // @synthesize otherInvitedHandles=_otherInvitedHandles;
@property(copy, nonatomic) NSSet *rejectedMembers; // @synthesize rejectedMembers=_rejectedMembers;
@property(copy, nonatomic) NSSet *kickedMembers; // @synthesize kickedMembers=_kickedMembers;
@property(copy, nonatomic) NSSet *pendingMembers; // @synthesize pendingMembers=_pendingMembers;
@property(copy, nonatomic) NSSet *lightweightMembers; // @synthesize lightweightMembers=_lightweightMembers;
@property(copy, nonatomic) NSSet *remoteMembers; // @synthesize remoteMembers=_remoteMembers;
@property(readonly, nonatomic) TUConversationMember *localMember; // @synthesize localMember=_localMember;
@property(readonly, nonatomic) TUHandle *initiator; // @synthesize initiator=_initiator;
@property(nonatomic, getter=hasJoined) _Bool hasJoined; // @synthesize hasJoined=_hasJoined;
@property(retain, nonatomic) TUConversationMember *localLightweightSecondaryMember; // @synthesize localLightweightSecondaryMember=_localLightweightSecondaryMember;
@property(readonly, nonatomic, getter=isLocallyCreated) _Bool locallyCreated; // @synthesize locallyCreated=_locallyCreated;
@property(nonatomic) long long letMeInRequestState; // @synthesize letMeInRequestState=_letMeInRequestState;
@property(nonatomic) _Bool hasReceivedLetMeInRequest; // @synthesize hasReceivedLetMeInRequest=_hasReceivedLetMeInRequest;
@property(nonatomic) long long state; // @synthesize state=_state;
@property(readonly, nonatomic) NSUUID *messagesGroupUUID; // @synthesize messagesGroupUUID=_messagesGroupUUID;
@property(retain, nonatomic) TUConversationLink *link; // @synthesize link=_link;
@property(readonly, nonatomic) NSUUID *groupUUID; // @synthesize groupUUID=_groupUUID;
@property(readonly, nonatomic) NSUUID *UUID; // @synthesize UUID=_UUID;
@property(nonatomic) __weak id <CSDConversationDelegate> delegate; // @synthesize delegate=_delegate;
- (void)activitySessionManager:(id)arg1 activitySessionStateChanged:(id)arg2 oldState:(unsigned long long)arg3;    // IMP=0x001000000003b541
- (void)activitySessionManager:(id)arg1 activitySessionRemoved:(id)arg2 userOriginated:(_Bool)arg3;    // IMP=0x001000000003b3bc
- (void)activitySessionManager:(id)arg1 requestForegroundPresentationForActivity:(id)arg2;    // IMP=0x001000000003b2a3
- (void)activitySessionManager:(id)arg1 sessionUnjoined:(id)arg2 startDate:(id)arg3 endDate:(id)arg4;    // IMP=0x001000000003b08d
- (id)activitySessionManagerRequestedCallTypeStringForLogging:(id)arg1;    // IMP=0x001000000003b024
- (void)activitySessionManager:(id)arg1 activityChangedOnSession:(id)arg2;    // IMP=0x001000000003af89
- (void)activitySessionManager:(id)arg1 activeRemoteParticipantWithParticipantIdentifier:(unsigned long long)arg2 bundleIdentifier:(id)arg3 completionHandler:(id)arg4;    // IMP=0x001000000003ad4b
- (id)activitySessionManager:(id)arg1 activeRemoteParticipantWithParticipantIdentifier:(unsigned long long)arg2 bundleIdentifier:(id)arg3;    // IMP=0x001000000003aba3
- (id)activitySessionManager:(id)arg1 localParticipantWithParticipantIdentifier:(unsigned long long)arg2 bundleIdentifier:(id)arg3;    // IMP=0x001000000003aa23
- (void)activitySessionManager:(id)arg1 requestEncryptionKeysForParticipants:(id)arg2 topicName:(id)arg3;    // IMP=0x001000000003a96a
- (void)activitySessionManager:(id)arg1 fetchDataCryptorForTopic:(id)arg2 completionHandler:(id)arg3;    // IMP=0x001000000003a8b1
- (void)activitySessionManager:(id)arg1 receivedActivitySessionEvent:(id)arg2;    // IMP=0x001000000003a816
- (void)activitySessionManager:(id)arg1 activitySessionChanged:(id)arg2;    // IMP=0x001000000003a72a
- (void)postUserNotificationForUnsupportedScreenSharingActivity:(id)arg1 alternateReponseHandler:(id)arg2;    // IMP=0x001000000003a37f
- (void)audioPolicyManager:(id)arg1 sharePlayAllowedStateChanged:(_Bool)arg2;    // IMP=0x0010000000039e86
- (void)updateScreenEnabledForRemoteParticipants:(_Bool)arg1;    // IMP=0x0010000000039bfe
- (void)remoteParticipantWithIdentifier:(unsigned long long)arg1 updatedRemoteVideoEnabled:(_Bool)arg2;    // IMP=0x0010000000039975
- (void)remoteParticipantWithIdentifier:(unsigned long long)arg1 updatedRemoteAudioEnabled:(_Bool)arg2;    // IMP=0x00100000000396ec
- (void)session:(id)arg1 screenCaptureDidStart:(_Bool)arg2 withError:(id)arg3;    // IMP=0x00100000000395b6
- (void)remoteParticipantWithIdentifier:(unsigned long long)arg1 didChangeAudioPriority:(long long)arg2 videoPriority:(long long)arg3;    // IMP=0x0010000000039412
- (void)remoteParticipantWithIdentifier:(unsigned long long)arg1 updatedAudioPaused:(_Bool)arg2 streamToken:(long long)arg3;    // IMP=0x001000000003928c
- (void)addedRemoteParticipantWithIdentifier:(unsigned long long)arg1 audioEnabled:(_Bool)arg2 streamToken:(long long)arg3 screenToken:(long long)arg4;    // IMP=0x0010000000039092
- (void)remoteParticipantWithIdentifier:(unsigned long long)arg1 updatedScreenEnabled:(_Bool)arg2 streamToken:(long long)arg3 screenToken:(long long)arg4;    // IMP=0x0010000000038c75
- (void)remoteParticipantWithIdentifier:(unsigned long long)arg1 updatedVideoEnabled:(_Bool)arg2 streamToken:(long long)arg3 screenToken:(long long)arg4;    // IMP=0x0010000000038abd
- (void)remoteParticipantWithIdentifier:(unsigned long long)arg1 updatedAudioEnabled:(_Bool)arg2 streamToken:(long long)arg3 screenToken:(long long)arg4;    // IMP=0x0010000000038905
- (void)sessionShouldReconnect:(id)arg1;    // IMP=0x001000000003879e
- (void)session:(id)arg1 changedBytesOfDataUsed:(long long)arg2;    // IMP=0x001000000003869c
- (void)session:(id)arg1 changedOneToOneModeEnabled:(_Bool)arg2 didSucceed:(_Bool)arg3 error:(id)arg4;    // IMP=0x00100000000384ee
- (void)session:(id)arg1 changedLocalVideoPaused:(_Bool)arg2 didSucceed:(_Bool)arg3 error:(id)arg4;    // IMP=0x00100000000381e5
- (void)session:(id)arg1 changedLocalAudioPaused:(_Bool)arg2 didSucceed:(_Bool)arg3 error:(id)arg4;    // IMP=0x0010000000037edc
- (void)session:(id)arg1 changedScreenEnabled:(_Bool)arg2 didSucceed:(_Bool)arg3 error:(id)arg4;    // IMP=0x0010000000037a11
- (void)session:(id)arg1 changedLocalVideoEnabled:(_Bool)arg2 didSucceed:(_Bool)arg3 error:(id)arg4;    // IMP=0x00100000000374bc
- (void)session:(id)arg1 changedLocalAudioEnabled:(_Bool)arg2 didSucceed:(_Bool)arg3 error:(id)arg4;    // IMP=0x00100000000371b3
- (void)serverDisconnectedForSession:(id)arg1;    // IMP=0x001000000003709e
- (void)session:(id)arg1 didStopWithError:(id)arg2;    // IMP=0x0010000000036df5
- (void)session:(id)arg1 didDetectError:(id)arg2;    // IMP=0x0010000000036b4b
- (void)session:(id)arg1 didStart:(_Bool)arg2 error:(id)arg3;    // IMP=0x001000000003657c
- (int)_errorToAVCProviderEndedReason:(id)arg1 defaultProviderReason:(int)arg2;    // IMP=0x0010000000036334
- (void)sessionDidReceiveKeyUpdate:(id)arg1;    // IMP=0x00100000000362c0
- (void)session:(id)arg1 didUnregisterPluginAllocationInfo:(id)arg2;    // IMP=0x0010000000036133
- (void)session:(id)arg1 didRegisterPluginAllocationInfo:(id)arg2;    // IMP=0x0010000000036003
- (void)session:(id)arg1 didReceiveKickedParticipantIDs:(id)arg2 withCode:(unsigned int)arg3 withType:(unsigned short)arg4 isTruncated:(_Bool)arg5;    // IMP=0x0010000000034c93
- (void)session:(id)arg1 didReceiveReport:(id)arg2;    // IMP=0x0010000000034bd1
- (void)sessionDidTerminate:(id)arg1;    // IMP=0x0010000000034b01
- (void)session:(id)arg1 receivedActiveLightweightParticipantDestinationsByIdentifier:(id)arg2;    // IMP=0x001000000003483e
- (void)session:(id)arg1 receivedActiveParticipantDestinationsByIdentifier:(id)arg2;    // IMP=0x0010000000034361
- (void)session:(id)arg1 endedWithError:(id)arg2 reason:(unsigned int)arg3;    // IMP=0x001000000003402f
- (void)session:(id)arg1 didLeaveGroupWithError:(id)arg2;    // IMP=0x0010000000033b62
- (void)session:(id)arg1 didJoinGroup:(_Bool)arg2 participantIdentifiers:(id)arg3 error:(id)arg4;    // IMP=0x001000000003379e
- (void)switchBackToOneToOneIfPossibleUsingDelay:(_Bool)arg1;    // IMP=0x0010000000032e68
- (void)switchBackToOneToOneIfPossible;    // IMP=0x0010000000032e54
- (void)_registerPluginsIfNecessary;    // IMP=0x0010000000032c5a
- (id)_stableExpanseIdentifier;    // IMP=0x00100000000328b2
- (void)_reportConversationFailedWithProviderEndedReason:(unsigned long long)arg1;    // IMP=0x00100000000327f4
- (void)_reportConversationFailedWithFailureReason:(long long)arg1 providerEndedReason:(unsigned long long)arg2;    // IMP=0x0010000000032723
- (void)refreshActiveParticipantsList;    // IMP=0x00100000000324bf
- (void)_pruneRemoteParticipantsIfNecessary;    // IMP=0x0010000000031f35
- (void)_cancelInFlightAVCBlobRecoveryIfNecessary;    // IMP=0x0010000000031b95
- (void)_requestAVCBlobsIfNecessary;    // IMP=0x0010000000031080
- (void)_cancelTimeoutForLeavingConversation;    // IMP=0x0010000000030fbe
- (void)_beginTimeoutForLeavingConversationWithReason:(id)arg1;    // IMP=0x0010000000030c19
- (void)_cleanUpFromAVCSessionFailure;    // IMP=0x0010000000030afb
- (void)_startAVCSessionIfNecessary;    // IMP=0x001000000003078f
- (void)_startIDSSessionWithContext:(id)arg1;    // IMP=0x0010000000030242
@property(readonly, nonatomic) _Bool allParticipantsSupportSharePlay;
- (void)addAliasesToConversationContainer:(id)arg1 forBundleIdentifier:(id)arg2;    // IMP=0x001000000002fff1
@property(readonly, nonatomic) TUConversationParticipant *localParticipant;
- (id)remoteMemberForHandle:(id)arg1;    // IMP=0x001000000002fd63
- (id)remoteParticipantForIdentifier:(unsigned long long)arg1;    // IMP=0x001000000002fc15
- (id)remoteParticipantForHandle:(id)arg1;    // IMP=0x000000000002f89c
- (void)addRequiredCapabilities:(id)arg1 requiredLackOfCapabilities:(id)arg2;    // IMP=0x001000000002f816
@property(readonly, nonatomic) NSDictionary *capabilitySendMessageOptions;
- (_Bool)containsMemberWithHandle:(id)arg1;    // IMP=0x001000000002f671
- (id)memberWithHandle:(id)arg1;    // IMP=0x001000000002f2dc
- (_Bool)isRepresentedByRemoteMembers:(id)arg1 andLink:(id)arg2;    // IMP=0x001000000002f0ac
- (id)reducedInfoMembers:(id)arg1;    // IMP=0x001000000002ee23
- (void)setVideoEnabled:(_Bool)arg1 forParticipantWithIdentifier:(unsigned long long)arg2;    // IMP=0x001000000002ed7e
- (void)setAudioEnabled:(_Bool)arg1 forParticipantWithIdentifier:(unsigned long long)arg2;    // IMP=0x001000000002ecd9
- (void)setRemoteParticipantsDownlinkMuted:(_Bool)arg1;    // IMP=0x001000000002eb11
- (void)_allowMember:(id)arg1;    // IMP=0x001000000002ea71
- (void)kickMember:(id)arg1;    // IMP=0x001000000002e776
- (void)leave;    // IMP=0x001000000002e1b2
- (void)startAudio;    // IMP=0x001000000002df9a
- (void)broadcastLocalParticipantData;    // IMP=0x001000000002de15
- (void)joinUsingContext:(id)arg1;    // IMP=0x001000000002d064
- (void)stopSelectiveSharingSession;    // IMP=0x001000000002d05e
- (void)resetSelectiveSharingSessionContent;    // IMP=0x001000000002d058
- (void)createSelectiveSharingSessionIfNecessary;    // IMP=0x001000000002d052
- (struct CGSize)localPortraitAspectRatio;    // IMP=0x001000000002cf75
@property(readonly, copy, nonatomic) NSSet *tuActivitySessions;
@property(readonly, copy, nonatomic) NSSet *activitySessions;
- (void)_launchApplicationForActivityIfNecessary:(_Bool)arg1;    // IMP=0x001000000002c2d3
- (void)_launchApplicationForActivityIfNecessary;    // IMP=0x001000000002c2ac
- (void)removeActivitySessionIfNecessary;    // IMP=0x001000000002bfc0
- (void)launchAppForActivity:(id)arg1 foreground:(_Bool)arg2 completionHandler:(id)arg3;    // IMP=0x001000000002bbec
- (void)launchAppForActivity:(id)arg1 completionHandler:(id)arg2;    // IMP=0x001000000002bb89
- (id)createStagedActivitySessionForActivity:(id)arg1;    // IMP=0x001000000002b760
- (id)createActivitySession:(id)arg1;    // IMP=0x001000000002ad9d
- (void)_launchApplicationDueToActivityCreation:(id)arg1;    // IMP=0x001000000002abb2
- (void)removeActivitySessionWithUUID:(id)arg1 usingTerminatingHandle:(id)arg2;    // IMP=0x001000000002aa2c
- (void)presentDismissalAlertForActivitySessionWithUUID:(id)arg1;    // IMP=0x001000000002a811
- (void)leaveActivitySessionWithUUID:(id)arg1;    // IMP=0x001000000002a6a7
- (_Bool)setConversationLink:(id)arg1 allowUpdate:(_Bool)arg2;    // IMP=0x001000000002a263
- (void)removePendingMembers:(id)arg1 triggeredLocally:(_Bool)arg2;    // IMP=0x0010000000029cfb
- (void)addPendingMembers:(id)arg1 triggeredLocally:(_Bool)arg2;    // IMP=0x001000000002976a
- (void)updateMessagesGroupName:(id)arg1;    // IMP=0x0010000000029711
- (void)updateMemberValidationSource:(id)arg1 source:(long long)arg2;    // IMP=0x0010000000029070
- (void)addRemoteMembers:(id)arg1 otherInvitedHandles:(id)arg2 invitationPreferences:(id)arg3 addingFromLetMeIn:(_Bool)arg4 triggeredLocally:(_Bool)arg5;    // IMP=0x0010000000027763
- (void)addRemoteMembers:(id)arg1 otherInvitedHandles:(id)arg2 triggeredLocally:(_Bool)arg3;    // IMP=0x00100000000276bb
- (void)removeRemoteMembers:(id)arg1 triggeredLocally:(_Bool)arg2;    // IMP=0x0010000000027021
- (void)removeVirtualParticipant:(id)arg1;    // IMP=0x0010000000026c6e
- (void)addVirtualParticipant:(id)arg1;    // IMP=0x001000000002691e
- (void)updateParticipantPresentationContexts:(id)arg1;    // IMP=0x00100000000265ae
- (void)removeParticipantWithIdentifier:(unsigned long long)arg1 fromHandle:(id)arg2;    // IMP=0x0010000000025da8
- (_Bool)allowsScreenSharing;    // IMP=0x0010000000025d1c
- (void)removeParticipantsForMember:(id)arg1;    // IMP=0x00100000000259da
- (void)addActiveParticipant:(id)arg1;    // IMP=0x0010000000024ecb
@property(copy, nonatomic) NSSet *memberIdentifiers; // @synthesize memberIdentifiers=_memberIdentifiers;
@property(nonatomic, getter=isFromStorage) _Bool fromStorage; // @synthesize fromStorage=_fromStorage;
- (void)updateLocalAspectRatiosForOneToOneModeEnabled:(_Bool)arg1;    // IMP=0x0010000000024cdd
- (void)setConversationGridDisplayMode:(unsigned long long)arg1;    // IMP=0x0010000000024c5a
@property(nonatomic) struct CGRect presentationRect;
@property(nonatomic) int presentationState;
@property(nonatomic, getter=isOneToOneModeEnabled) _Bool oneToOneModeEnabled;
@property(nonatomic, getter=isVideo) _Bool video; // @synthesize video=_video;
@property(nonatomic, getter=isRelaying) _Bool relaying; // @synthesize relaying=_relaying;
@property(nonatomic, getter=isAudioPaused) _Bool audioPaused;
@property(nonatomic, getter=isVideoPaused) _Bool videoPaused;
- (void)setScreenEnabled:(_Bool)arg1 attributes:(id)arg2;    // IMP=0x001000000002366c
@property(nonatomic, getter=isVideoEnabled) _Bool videoEnabled;
@property(readonly, nonatomic, getter=isScreenEnabled) _Bool screenEnabled;
@property(nonatomic, getter=isAudioEnabled) _Bool audioEnabled;
@property(nonatomic, getter=isUplinkMuted) _Bool uplinkMuted;
@property(readonly, nonatomic) NSSet *virtualParticipants;
- (_Bool)_expanseEnabled;    // IMP=0x0010000000022a51
- (id)localParticipantDataToSendToDestinationIDs:(id)arg1;    // IMP=0x001000000002295d
- (id)localParticipantData;    // IMP=0x00100000000226ff
- (id)localConversationParticipantWithDataToSendToDestinationIDs:(id)arg1;    // IMP=0x001000000002261d
@property(readonly, nonatomic, getter=isAudioReady) _Bool audioReady;
- (long long)maxVideoDecodesAllowed;    // IMP=0x001000000002232d
- (unsigned long long)localParticipantIdentifier;    // IMP=0x00100000000222b4
@property(readonly, nonatomic) long long avcSessionToken;
- (id)avcSessionIdentifier;    // IMP=0x00100000000221b6
@property(readonly, copy, nonatomic) TUConversation *tuConversation;
@property(readonly, nonatomic) _Bool isAnyOtherAccountDeviceActive;
@property(readonly, copy, nonatomic) NSSet *activeLightweightParticipants;
@property(readonly, copy, nonatomic) NSSet *activeRemoteParticipants;
- (id)activeParticipants;    // IMP=0x0010000000021405
@property(readonly, copy) NSString *description;
- (id)initWithQueue:(id)arg1 UUID:(id)arg2 groupUUID:(id)arg3 groupSession:(id)arg4 messagesGroupUUID:(id)arg5 locallyCreated:(_Bool)arg6 localMember:(id)arg7 initiator:(id)arg8 remoteMembers:(id)arg9 pendingMembers:(id)arg10 otherInvitedHandles:(id)arg11 lightweightMembers:(id)arg12 activity:(id)arg13 link:(id)arg14 report:(id)arg15 fromStorage:(_Bool)arg16 video:(_Bool)arg17 applicationController:(id)arg18 featureFlags:(id)arg19 systemStateObserver:(id)arg20;    // IMP=0x001000000001fb37
- (id)initWithQueue:(id)arg1 UUID:(id)arg2 groupUUID:(id)arg3 groupSession:(id)arg4 messagesGroupUUID:(id)arg5 locallyCreated:(_Bool)arg6 localMember:(id)arg7 initiator:(id)arg8 remoteMembers:(id)arg9 pendingMembers:(id)arg10 otherInvitedHandles:(id)arg11 lightweightMembers:(id)arg12 activity:(id)arg13 link:(id)arg14 report:(id)arg15 fromStorage:(_Bool)arg16 video:(_Bool)arg17 applicationController:(id)arg18;    // IMP=0x001000000001f919

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end
