# Uncomment the next line to define a global platform for your project
platform :macos, '10.15'

target 'BlueBubblesHelper' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for BlueBubblesHelper

   pod 'CocoaAsyncSocket'

end

target 'BlueBubblesHelper DyLib' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for BlueBubblesHelper

   pod 'CocoaAsyncSocket'

end

workspace 'BlueBubblesHelper'
