//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//


@interface ETiOSMacBalloonPluginDataSource : NSObject {}

@property (readonly, nonatomic) NSString* assetURLPath;
@property (readonly, nonatomic) NSURL* assetURL;
@property (readonly, nonatomic) NSURL* assetPreviewURL;

- (id) _createImageForMessage;
- (id) _mediaPathForMessagePreview;
- (id) assetPreviewURL;
- (void) generateMedia:(id)arg1;
- (BOOL) canProvideSize;
- (struct CGSize) sizeThatFits:(struct CGSize)arg1;
- (id) assetURL;
- (id) initWithPluginPayload:(id)arg1;
- (id) assetURLPath;

@end
