/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, October 12, 2021 at 10:43:57 PM Eastern Daylight Time
* Operating System: Version 11.1 (Build 20C5061b)
* Image Source: /System/Library/PrivateFrameworks/IMCore.framework/Versions/A/IMCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import "IMFileTransferCenter.h"

@protocol IMFileTransferCenter <NSObject>
@required
-(id)guidForNewOutgoingTransferWithLocalURL:(id)arg1;
-(void)registerTransferWithDaemon:(id)arg1;

@end


@class NSMutableDictionary, NSMutableArray, NSMutableSet, NSDictionary, NSArray, NSString;

@interface IMFileTransferCenter : NSObject <IMFileTransferCenter> {

    NSMutableDictionary* _guidToTransferMap;
    NSMutableDictionary* _guidToRemovedTransferMap;
    NSMutableDictionary* _accountIDToTransferGUIDsMap;
    NSMutableArray* _preauthorizedInfos;
    NSMutableArray* _preauthorizedGUIDs;
    NSMutableSet* _activeTransfers;
    NSMutableSet* _pendingTransfers;
    char _disconnectionListenerSetUp;
    NSMutableDictionary* _fetchHighQualityVariantCompletionHandlers;
    char _issueSandboxEstensionsForTransfers;

}

@property (nonatomic,readonly) NSDictionary * transfers;
@property (nonatomic,readonly) NSArray * activeTransferGUIDs;
@property (nonatomic,readonly) NSArray * orderedTransfersGUIDs;
@property (nonatomic,readonly) char hasActiveFileTransfers;
@property (nonatomic,readonly) char hasPendingFileTransfers;
@property (assign,getter=shouldIssueSandboxEstensionsForTransfers,nonatomic) char issueSandboxEstensionsForTransfers;              //@synthesize issueSandboxEstensionsForTransfers=_issueSandboxEstensionsForTransfers - In the implementation block
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (copy,readonly) NSString * description;
@property (copy,readonly) NSString * debugDescription;
+(id)sharedInstance;
+(Class)transferCenterClass;
+(Class)fileTransferClass;
+(void)setTransferCenterClass:(Class)arg1 ;
-(void)dealloc;
-(NSDictionary *)transfers;
-(void)removeTransfer:(id)arg1 ;
-(void)stopTransfer:(id)arg1 ;
-(void)_addTransfer:(id)arg1 ;
-(id)transferForGUID:(id)arg1 ;
-(void)deleteTransfer:(id)arg1 ;
-(id)transfersForAccount:(id)arg1 ;
-(void)_handleFileTransfer:(id)arg1 createdWithProperties:(id)arg2 ;
-(void)_handleFileTransfers:(id)arg1 createdWithLocalPaths:(id)arg2 ;
-(void)_handleFileTransfer:(id)arg1 updatedWithProperties:(id)arg2 ;
-(void)_handleFileTransfer:(id)arg1 updatedWithCurrentBytes:(unsigned long long)arg2 totalBytes:(unsigned long long)arg3 averageTransferRate:(unsigned long long)arg4 ;
-(void)_handleFileTransfer:(id)arg1 highQualityDownloadSucceededWithPath:(id)arg2 ;
-(void)_handleFileTransferHighQualityDownloadFailed:(id)arg1 ;
-(void)_handleAllFileTransfers:(id)arg1 ;
-(void)_removePendingTransfer:(id)arg1 ;
-(void)_removeActiveTransfer:(id)arg1 ;
-(void)_removeAllActiveTransfers;
-(void)acknowledgeAllPendingTransfers;
-(void)_addTransfer:(id)arg1 toAccount:(id)arg2 ;
-(void)_addPendingTransfer:(id)arg1 ;
-(id)guidForNewOutgoingTransferWithLocalURL:(id)arg0 useLegacyGuid:(BOOL)arg1 ;
-(char)shouldIssueSandboxEstensionsForTransfers;
-(id)chatForTransfer:(id)arg1 ;
-(void)_addSpotlightProperties:(id)arg1 sender:(id)arg2 recipients:(id)arg3 incoming:(char)arg4 ;
-(char)doesLocalURLRequireArchiving:(id)arg1 toHandle:(id)arg2 ;
-(id)transferForGUID:(id)arg1 includeRemoved:(char)arg2 ;
-(void)_addActiveTransfer:(id)arg1 ;
-(void)acceptTransfer:(id)arg1 withPath:(id)arg2 autoRename:(char)arg3 overwrite:(char)arg4 ;
-(char)isFileTransfer:(id)arg1 preauthorizedWithDictionary:(id)arg2 ;
-(void)_clearTransfers;
-(void)acceptFileTransferIfPreauthorzed:(id)arg1 ;
-(char)registerGUID:(id)arg1 forNewOutgoingTransferWithLocalURL:(id)arg2 ;
-(id)guidForNewOutgoingTransferWithLocalURL:(id)arg1 ;
-(void)_fetchHighQualityVariantForTransferGUID:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)_daemonRestarted:(id)arg1 ;
-(void)_initiateHighQualityVariantDownloadWithDaemonForGUID:(id)arg1 ;
-(void)registerTransferWithDaemon:(id)arg1 ;
-(char)hasPendingFileTransfers;
-(void)acknowledgePendingTransfer:(id)arg1 ;
-(char)hasActiveFileTransfers;
-(void)assignTransfer:(id)arg1 toMessage:(id)arg2 account:(id)arg3 ;
-(void)assignTransfer:(id)arg1 toHandle:(id)arg2 ;
-(void)sendTransfer:(id)arg1 ;
-(void)acceptTransfer:(id)arg1 ;
-(void)retargetTransfer:(id)arg1 toPath:(id)arg2 ;
-(NSArray *)activeTransfers;
-(NSArray *)activeTransferGUIDs;
-(NSArray *)orderedTransfers;
-(NSArray *)orderedTransfersGUIDs;
-(void)clearFinishedTransfers;
-(void)preauthorizeFileTransferFromOtherPerson:(id)arg1 account:(id)arg2 filename:(id)arg3 saveToPath:(id)arg4 ;
-(char)wasFileTransferPreauthorized:(id)arg1 ;
-(void)setAuxImageForTransfer:(id)arg1 value:(char)arg2 ;
-(void)setAuxVideoForTransfer:(id)arg1 value:(char)arg2 ;
-(id)guidsForStoredAttachmentPayloadData:(id)arg1 messageGUID:(id)arg2 ;
-(void)fetchHighQualityVariantForTransfer:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)preWarmConnection;
-(void)setIssueSandboxEstensionsForTransfers:(char)arg1 ;
@end
