/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, October 12, 2021 at 10:43:57 PM Eastern Daylight Time
* Operating System: Version 11.1 (Build 20C5061b)
* Image Source: /System/Library/PrivateFrameworks/IMCore.framework/Versions/A/IMCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import "IMMessagePartChatItem.h"
#import "IMPluginChatItemProtocol.h"

@class NSString, IMBalloonPluginDataSource, IMPluginPayload;

@interface IMTranscriptPluginChatItem : IMMessagePartChatItem <IMPluginChatItemProtocol> {

    char _isLastChatItemOfPluginType;
    char _hasSetIsLastChatItemOfPluginType;
    char _parentChatHasKnownParticipants;
    IMPluginPayload* _initialPayload;
    NSString* _bundleIdentifier;
    IMBalloonPluginDataSource* _dataSource;

}

@property (nonatomic,retain) IMBalloonPluginDataSource * dataSource;                                           //@synthesize dataSource=_dataSource - In the implementation block
@property (nonatomic,retain) IMPluginPayload * initialPayload;                                                 //@synthesize initialPayload=_initialPayload - In the implementation block
@property (nonatomic,retain) NSString * bundleIdentifier;                                                      //@synthesize bundleIdentifier=_bundleIdentifier - In the implementation block
@property (assign,nonatomic) char hasSetIsLastChatItemOfPluginType;                                            //@synthesize hasSetIsLastChatItemOfPluginType=_hasSetIsLastChatItemOfPluginType - In the implementation block
@property (nonatomic,readonly) char isDataSourceInitialized;
@property (nonatomic,readonly) NSString * pluginSessionGUID;
@property (nonatomic,readonly) unsigned long long playbackType;
@property (assign,setter=setLastChatItemOfPluginType:,nonatomic) char isLastChatItemOfPluginType;              //@synthesize isLastChatItemOfPluginType=_isLastChatItemOfPluginType - In the implementation block
@property (nonatomic,readonly) char parentChatHasKnownParticipants;                                            //@synthesize parentChatHasKnownParticipants=_parentChatHasKnownParticipants - In the implementation block
@property (nonatomic,readonly) char isPlayed;
@property (nonatomic,readonly) char isSaved;
@property (nonatomic,retain,readonly) NSString * type;
@property (nonatomic,readonly) char isFromMe;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (copy,readonly) NSString * description;
@property (copy,readonly) NSString * debugDescription;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSString *)description;
-(NSString *)type;
-(NSString *)bundleIdentifier;
-(void)setBundleIdentifier:(NSString *)arg1 ;
-(IMBalloonPluginDataSource *)dataSource;
-(void)setDataSource:(IMBalloonPluginDataSource *)arg1 ;
-(unsigned long long)playbackType;
-(char)isSaved;
-(char)isPlayed;
-(NSString *)pluginSessionGUID;
-(id)_initWithItem:(id)arg1 initialPayload:(id)arg2 index:(long long)arg3 messagePartRange:(NSRange)arg4 parentChatHasKnownParticipants:(char)arg5 ;
-(id)replyContextPreviewChatItemForReply:(id)arg1 ;
-(IMPluginPayload *)initialPayload;
-(char)parentChatHasKnownParticipants;
-(void)setInitialPayload:(IMPluginPayload *)arg1 ;
-(char)hasSetIsLastChatItemOfPluginType;
-(char)isLastChatItemOfPluginType;
-(char)isDataSourceInitialized;
-(void)setLastChatItemOfPluginType:(char)arg1 ;
-(char)wantsAutoPlayback;
-(void)setHasSetIsLastChatItemOfPluginType:(char)arg1 ;
@end
